version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitProjectStagingProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: WmSalesforceProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.newgitprojectstaging.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:SF_1
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: project.newgitprojectstaging.integrations:DAFService
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.newgitprojectstaging.integrations:SF
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: projectstaging.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:QueryAcc
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
configurationVariables:
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.connectTimeout
  : "180000"
  ? iscloudstreamsconnectorservice.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:QueryAcc.virtualServiceName
  : WmCloudStreams.SoapVS
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cr.password
  : "{AES}OYSjbNfOLUKJAT+MWJt0w3FPbUooYAcCzhGF0UMKgsfxDQ1MMLJvU+e5tmiaXP+/"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.rh.requestHeaderValues
  : "text/xml,login"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cr.username
  : rithi@softwareag.com
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.timeoutType
  : fixed
  ? iscloudstreamsconnectorservice.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:QueryAcc.connectionAlias
  : project.newgitprojectstaging.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:SF_1
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.poolable
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.pr.followServerRedirects
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_1.pr.httpContentCharSet
  : ISO-8859-1
