version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitProjectStagingProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
- name: WmSalesforceProvider
  version: 10.7.0.0.66
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
services:
- serviceName: project.newgitprojectstaging.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:SF_2
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: project.newgitprojectstaging.integrations:DAFService
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
- serviceName: project.newgitprojectstaging.integrations:SF
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: projectstaging.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:QueryAcc
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: project.newgitprojectstaging.integrations:SF_1
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
- serviceName: projectstaging.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.operations.actions:QAcc
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.66
configurationVariables:
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.sessionExpiry
  : "14"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.rh.requestHeaderValues
  : "text/xml,login"
  ? iscloudstreamsconnectorservice.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:QAcc.virtualServiceName
  : WmCloudStreams.SoapVS
  ? iscloudstreamsconnectorservice.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..operations..actions:QAcc.connectionAlias
  : project.newgitprojectstaging.WmSalesforceProvider.com_softwareag_cloudstreams_salesforce_v53.connections:SF_2
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.connectionEnabled
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.readTimeout
  : "180000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cr.username
  : rithi@softwareag.com
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.pr.useExpectCont
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.providerUrl
  : https://login.salesforce.com/services/Soap/u/53.0
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.pr.httpContentCharSet
  : ISO-8859-1
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.poolable
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cr.preemptiveAuthEnabled
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.retryCount
  : "3"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.pr.userAgent
  : Cloudstreams
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.timeoutType
  : fixed
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.pr.protocolVersion
  : HTTP/1.1
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.pr.allowCircularRedirects
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.pr.serverRedirectMax
  : "5"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.rh.requestHeaderNames
  : "Content-Type,SOAPAction"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cr.authSchemeType
  : none
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cr.password
  : "{AES}OYSjbNfOLUKJAT+MWJt0w3FPbUooYAcCzhGF0UMKgsfxDQ1MMLJvU+e5tmiaXP+/"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.connectTimeout
  : "180000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.pr.useChunking
  : "false"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..newgitprojectstaging..WmSalesforceProvider..com_softwareag_cloudstreams_salesforce_v53..connections:SF_2.pr.followServerRedirects
  : "true"
