version: "1.0"
info:
  model: int-scaffold
packages:
- name: NewGitProjectStagingProject
  gitServerName: GithubOrigin
  gitUrl: https://github.com/Munatri
  gitUsername: Munatri
  gitBranch: main
services:
- serviceName: project.newgitprojectstaging.integrations:DAFService
  packages:
  - name: NewGitProjectStagingProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
